services:
  postgres:
    image: postgres:16-alpine
    container_name: cigua_postgres
    environment:
      POSTGRES_DB: cigua_inv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eli112910
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cigua_inv"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
